# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "76b991048771fb5d9cd2f0d75081d3db"
name = "eenour-2024-11-04"
handle = "eenour-2024-11-04"
application_url = "https://jr-andorra-leading-sega.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "eenour-test-shop.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jr-andorra-leading-sega.trycloudflare.com/auth/callback",
  "https://jr-andorra-leading-sega.trycloudflare.com/auth/shopify/callback",
  "https://jr-andorra-leading-sega.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
